name: "release"
on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
      TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
      TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: install app dependencies and build it
        run: yarn && yarn tauri:build

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bundles
          path: src-tauri/target/release/bundle/msi

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.PAT }}

      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: bundles
          path: ./release

      - name: change updater signature
        shell: bash
        run: |
          cd ./release
          tag=`sed 's/^v\(.*\)/\1/' <<<"${{ steps.vars.outputs.tag }}"`
          value=`cat './LudumDareViewer_'$tag'_x64_en-US.msi.zip.sig'`
          cd ../
          pub_date=$(date --rfc-3339=sec)
          cat <<<$(jq '.pub_date |= "'$pub_date'"' update.json) >update.json
          cat <<<$(jq '.version |= "'$tag'"' update.json) >update.json
          cat <<<$(jq '.platforms."windows-x86_64".signature |= "'$value'"' update.json) >update.json
          cat <<<$(jq '.platforms."windows-x86_64".url |= "https://github.com/ikiselev1989/ld-viewer-desktop/releases/download/'$tag'/LudumDareViewer_'$tag'_x64_en-US.msi.zip"' update.json) >update.json

      - name: Commit report
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Automatic update'
          commit_user_name: Ilya Kiselev
          commit_user_email: ikiselev1989@gmail.com
          commit_author: Ilya Kiselev <ikiselev1989@gmail.com>

      - name: Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: ./release/*.msi
          allowUpdates: true
