name: "release"
on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        platform: [ windows-latest ]

    runs-on: ${{ matrix.platform }}
    env:
      TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
      TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: install app dependencies and build it
        run: yarn && yarn tauri:build

      - name: change updater signature
        shell: bash
        run: |
          value=`cat src-tauri/target/release/bundle/msi/LudumDareViewer_*.msi.sig`
          cat <<<$(jq '.platforms."windows-x86_64".signature |= "'$value'"' update.json) >update.json

      - name: commit and push updater signature
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_prefix: "[AUTO] updater signature"

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bundles
          path: src-tauri/target/release/bundle/msi

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2

      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: bundles
          path: release

      - name: Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: release/*.msi.zip, release/*.msi
          allowUpdates: true
