name: "release"
on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
      TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
      TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: install app dependencies and build it
        run: yarn && yarn tauri:build

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bundles
          path: src-tauri/target/release/bundle/msi

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2

      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: bundles
          path: release

      - uses: actions/checkout@v3
        with:
          toke: ${{ secrets.PAT }}

      - name: change updater signature
        shell: bash
        run: |
          tag=`sed 's/^v\(.*\)/\1/' <<<"${{ steps.vars.outputs.tag }}"`
          value=`cat 'release/LudumDareViewer_'$tag'_x64_en-US.msi.zip.sig'`
          cat <<<$(jq '.platforms."windows-x86_64".signature |= "'$value'"' update.json) >update.json

      - name: Commit report
        run: |
          git config user.name 'Ilya Kiselev'
          git config user.email 'ikiselev1989@gmail.com'
          git commit -am "Automated update"
          git push

      - name: Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: release/*.msi.zip, release/*.msi
          allowUpdates: true
